### PR TITLE
new: [tests] Create test foundations

### PR DESCRIPTION
**Pull request by cvandeplas**
- [x] foundations of tests for ubuntu + mac testing
- [x] find/generate test data that can be published publicly - as git submodule 
- [x] allow private test data in `testdata-private` folder 
- [x] parser - basic tests
- [x] unify parser main function and params
- [x] adapt `parsing.py` and `initialise.py` to new function call 
- [x] adapt analysers to new data format
- [x] analysers - basic tests (for later ... or not)

### CODE REVIEW

**Comment by cvandeplas** [comment]
Meant to also address issues #40 , #41

**Comment by aaronkaplan** [comment]
I can check out the repo and test on a Mac.

**Comment by cvandeplas** [comment]
No worries @aaronkaplan , I now also have a mac at my disposal.

**Comment by aaronkaplan** [comment]
excellent

**Comment by cvandeplas** [comment]
@aaronkaplan  A review is already welcome. Feel free to make changes and push to the branch.
I'll continue to work on the `parsers.py` and `initialise.py` parts before full merge.

**Comment by cvandeplas** [comment]
Analyzer tests will be covered later, with issue #40

**Comment by cvandeplas** [comment]
Last test broke on MacOS:
```
  File "/Users/runner/work/sysdiagnose/sysdiagnose/analysers/apps.py", line 86, in analyse_path
    for entry in ijson.items(f, 'data.item'):
ijson.common.IncompleteJSONError: parse error: trailing garbage
          parentActivityIdentifier":0} {"timezoneName":"","eventType":
                     (right here) ------^
```

**Comment by cvandeplas** [comment]
Linux test will break until PR https://github.com/mandiant/macos-UnifiedLogs/pull/18 is merged.

**Comment by cvandeplas** [comment]
wooohoo, tests are now fine as unifiedlog_parser_json patch has been accepted !

**Pull request merged**
